#!/bin/bash

# Description: Link dotfiles to home directory

mkdir -p ~/.config

dotfiles=("bashr" "vimrc")

link_file(){
    for dotfile in "$@"; do
        ln -sf ~/dotfiles/"$dotfile" ~/."$dotfile"
        echo "Linked: $dotfile"
    done
}

link_file "${dotfiles[@]}"

ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml

echo "Dotfiles linked!"
