#!/bin/bash

# Description: Link dotfiles to home directory

mkdir -p ~/.config

dotfiles=("bashrc" "vimrc")

link_file(){
    for dotfile in "$@"; do
        ln -sf ~/dotfiles/"$dotfile" ~/."$dotfile"
        echo "Linked: $dotfile"
    done
}

link_file "${dotfiles[@]}"

ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml

# Run Vim headlessly to install/update plugins without opening the UI
echo "Installing Vim plugins..."
vim +PlugInstall +qall

echo "Dotfiles linked!"
