# Fix the terminal colors
set -g default-terminal "screen-256color"

# RELOAD SHORTCUT
unbind r
bind r source-file ~/.tmux.conf \; display "Config Reloaded!"

# THE INDICATOR (The whole bar turns YELLOW)
set -g status-style "#{?client_prefix,bg=yellow,fg=black,bg=black,fg=white}"

# THE LEFT SIDE (Session Name)
# Logic: If Prefix, show RED. Else, show GREEN.
set -g status-left-length 21
set -g status-left "#{?client_prefix,#[bg=red]#[fg=white] #S ,#[bg=green]#[fg=black] #S } "

# THE RIGHT SIDE
# Ensure there is enough room to show the text
set -g status-right-length 100

# The Logic: Show Folder Name + (COMMAND Alert if Prefix is pressed) + Clock
set -g status-right "#{?client_prefix,#[bg=red]#[fg=white] COMMAND ACTIVE #[default] ,} #[fg=yellow]#{=20:pane_current_path} #[fg=cyan]%H:%M "

# Force the bar to update every second so the "COMMAND" appears instantly
set -g status-interval 1

# This makes the ACTIVE window blue and the others plain
set -g window-status-current-format "#[bg=blue,fg=white,bold] #I:#W#F #[default]"
set -g window-status-format " #I:#W#F "

